### ISSUE TITLE
[BUG] Touch not working in HP x360 14a chromebook (blooguard)

### ISSUE THREAD

**Issue by apandada1** [eupnea-linux/EupneaOS#10]
**Describe the bug**
I flashed EupneaOS on a USB and booted from it. The touch screen of my HP x360 14a chromebook (blooguard) is not working.

It says "No touchscreen found".

![image](https://user-images.githubusercontent.com/3063132/235828364-40a2dbd5-c045-4426-96c2-3d08d7747c1a.png)

**To Reproduce**
1. Flashed the latest build of EupneaOS from GitHub.
2. Booted the live USB by pressing `ctrl + U`

**Build system (please complete the following information):**
 - OS: I used Ubuntu 23.04 to join the files in https://github.com/eupnea-linux/EupneaOS/tags, and flashed it using the ChromeOS Firmware utility.

**Additional context**
I am happy to provide any necessary logs.

**Comment by Apacelus** [comment]
EupneaOS is not ready and should not be used. Please use [depthboot](https://github.com/eupnea-linux/depthboot-builder) instead

**Comment by apandada1** [comment]
I confirm that touch works out-of-the box with ChromeOS kernel (using depthboot) in Kubuntu 23.04. Automatic screen rotation in tablet mode works as well.

Sound works after running the `setup-audio` script.
