### ISSUE TITLE
Liveuser password 

### ISSUE THREAD

**Issue by tarasian666** [eupnea-linux/EupneaOS#2]
What is the default password for the liveuser?

**Comment by Apacelus** [comment]
Its `eupnea`

**Comment by tarasian666** [comment]
> Its `eupnea`

No it's `eupneaos`, found in script. 
It should be mentioned in readme file

**Comment by Apacelus** [comment]
> It should be mentioned in readme file

It's just there for testing. In the final version there will be no need for this password.
