### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by gaslec** [eupnea-linux/EupneaOS#6]
Does you plan to support arm64 chromebooks?

Cadmium and VelvetOS don't have support for Fedora (only debian-based, plus void for Cadmium), so that would be really nice to have an available option!

I have a trogdor based chromebook, I could run tests if you need! :)

**Comment by Apacelus** [comment]
Arm support is not currently planned.

Perhaps we will look into arm support, once we have finished everything in the [to-do list](https://github.com/orgs/eupnea-linux/projects)
